"""Init

Revision ID: 9224a50049d5
Revises: 
Create Date: 2023-06-19 11:39:01.259059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9224a50049d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lpus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lpus_id", sa.Integer(), nullable=True),
        sa.Column("lpus_name", sa.String(length=255), nullable=False),
        sa.Column("ogrn", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lpus_id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id"),
    )
    op.create_table(
        "specialties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_code", sa.Integer(), nullable=True),
        sa.Column("spec_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spec_code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("second_name", sa.String(length=64), nullable=True),
        sa.Column("snils", sa.String(length=12), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lpus_to_mo",
        sa.Column("lpus_id", sa.Integer(), nullable=False),
        sa.Column("mo_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lpus_id"],
            ["lpus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mo_id"],
            ["lpus.id"],
        ),
        sa.PrimaryKeyConstraint("lpus_id"),
    )
    op.create_table(
        "user_to_lpu",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("lpus_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lpus_id"],
            ["lpus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("users_id"),
    )
    op.create_table(
        "users_to_specialisation",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("spec_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["specialties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("users_id"),
    )
    op.create_table(
        "users_additional_info",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users_to_role",
        sa.Column("users_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("users_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_to_role")
    op.drop_table("users_additional_info")
    op.drop_table("users_to_specialisation")
    op.drop_table("user_to_lpu")
    op.drop_table("lpus_to_mo")
    op.drop_table("users")
    op.drop_table("specialties")
    op.drop_table("role")
    op.drop_table("lpus")
    # ### end Alembic commands ###
