"""Add index

Revision ID: cea7c3e4547c
Revises: 9224a50049d5
Create Date: 2023-06-19 11:39:22.647092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cea7c3e4547c"
down_revision = "9224a50049d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_role", "role", ["role_id"])
    op.create_index("idx_lpus", "lpus", ["lpus_id"])
    op.create_index("idx_specialties", "specialties", ["spec_code"])
    op.create_index("idx_users_additional_info", "users_additional_info", ["user_id"])
    op.create_index("idx_users_to_role", "users_to_role", ["users_id", "role_id"])
    op.create_index(
        "idx_users_to_specialisation",
        "users_to_specialisation",
        ["users_id", "spec_id"],
    )
    op.create_index("idx_user_to_lpu", "user_to_lpu", ["users_id", "lpus_id"])
    op.create_index("idx_lpus_to_mo", "lpus_to_mo", ["mo_id", "lpus_id"])
    op.create_index("idx_users", "users", ["login"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lpus", "lpus")
    op.drop_index("idx_role", "role")
    op.drop_index("idx_specialties", "specialties")
    op.drop_index("idx_users_additional_info", "users_additional_info")
    op.drop_index("idx_users_to_role", "users_to_role")
    op.drop_index("idx_users_to_specialisation", "users_to_specialisation")
    op.drop_index("idx_user_to_lpu", "user_to_lpu")
    op.drop_index("idx_lpus_to_mo", "lpus_to_mo")
    op.drop_index("idx_users", "users")
    op.create_index("idx_users", "users", ["login"])
    # ### end Alembic commands ###
